=== mohammedfaizaansharief1/wt_lab/week_6/books.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/xmlschema">
<!-- targetNamespace="http://my_namespace" xmlns="http:/my_namespace">-->
<xsd:element name="book-info">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="books" >
<!--minoccurs="1" maxoccrs="4">-->
<xsd:sequence>
<xsd:element name="titleofthebook" xsd:type="xsd:string"/><xsd:element name="Authorname" xsd:type="xsd:string"/>
<xsd:element name="ISBNnumber"xsd:type:"xsd:decimal"/>
<xsd:element name="edition" xsd:type:"xsd:string"/>
<xsd:element name="price" xsd:type:"xsd:decimal"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== mohammedfaizaansharief1/wt_lab/week_6/books.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="books.css"?>
<book-info xmlns="http://my_namespace" xmlns:xsi="http://www.w3.org/2001/xmlschema-instance" xsi:schemaLocation="http://my_namespace
e:\surekha\books.xsd">
<books>
<titleofthebook>web programming</titleofthebook>
<Authorname>chris bates</Authorname>
<ISBNnumber>123-333</ISBNnumber>
<publication>willy</publication>
<edition>2nd</edition>
<price>435</price>
</books>
<books>
<titleofthebook>compiler design</titleofthebook>
<Authorname>ulmon</Authorname>
<ISBNnumber>1223-333</ISBNnumber>
<publication>pearson</publication>
<edition>2nd</edition>
<price>475</price>
</books>
</book-info>
